### ISSUE TITLE
Need accept null in return types

### ISSUE THREAD

**Issue by sahartak** [slince/shopify-php-sdk#100]
return types generating error for null values, for example in class Slince\Shopify\Model\Orders\Order
public function getFulfillmentStatus(): string
    {
        return $this->fulfillmentStatus;
    }

need change return types to public function getFulfillmentStatus(): ?string {}

**Comment by slince** [comment]
hello, can you submit a pr for this?

**Comment by dashko** [comment]
This is an issue for us as well.

**Comment by happyclicker** [comment]
This. needs to be done pretty much everywhere - Shopify returns a null when it feels like it instead of a "".  Address, Order, Customer, everything.

**Comment by slince** [comment]
fixed in 3.0.2

**Comment by dashko** [comment]
This was not fixed in 3.0.2 @slince :

Return value of Slince\Shopify\Model\Orders\Order::getShippingAddress() must be an instance of Slince\Shopify\Model\Orders\Common\OrderAddress, null returned

**Comment by slince** [comment]
@dashko  fixed
