### ISSUE TITLE
API Deprecation at Shopify: 2021-10 Edition

### ISSUE THREAD

**Issue by aytackokus** [slince/shopify-php-sdk#104]
Hello,

One of our clients is using an older version of your package. Version 2.3.0 to be specific.
We are planning to upgrade this to 3.x.x, however we noticed that the supported API version is 2020-10.

Are you planning to upgrade the code to support the 2021-10 or 2021-01 edition? Because it seems that the version 2020-10 will be unsupported soon based on this article: https://www.shopify.com/partners/blog/shopify-api-release-october-2021

Take care,

Aytac

**Comment by slince** [comment]
Api version can be changed when initialize  client.

```php
$client = new Slince\Shopify\Client('your-store.myshopify.com', $credential, [
    'meta_cache_dir' => './tmp' ,
    'api_version' => '2021-10'
]);
```
