### ISSUE TITLE
Use psr/http-message instead of guzzle

### ISSUE THREAD

**Issue by garak** [slince/shopify-php-sdk#94]
This would allow users to choose their HTTP client of choice (even staying with guzzle itself)

**Comment by slince** [comment]
do you mean this package https://github.com/php-fig/http-client ?

**Comment by garak** [comment]
> do you mean this package https://github.com/php-fig/http-client ?

yes

**Comment by slince** [comment]
Although the idea is beautiful, It's not enough to rely on `php-fig/http-client`. You also need other package like `php-http/httplug` and  its adapter.  this will increase the complexity of the library
