### ISSUE TITLE
Returning null values after updating the library

### ISSUE THREAD

**Issue by Skreiphoff** [slince/shopify-php-sdk#99]
After updating the library, there is a problem with returning data from shopify, at the stage of transferring it to the controller. At the same time, the data comes from Shopify in a normal state, the problem can be solved by completely removing the vendor and rolling back the composer.lock. What could be the problem?

**Comment by slince** [comment]
Can you take a detailed screenshot and tell me your upgraded version

**Comment by jstoone** [comment]
Sounds a lot like a confused serializer @Skreiphoff. Would you mind taking a look at what I wrote in https://github.com/slince/shopify-api-php/issues/84#issuecomment-754911464? Maybe that should shed some light on what you're experiencing. ☺️ :v:

**Comment by Skreiphoff** [comment]
@jstoone, да ситуация схожа с одним из наших кейсов

**Comment by jstoone** [comment]
> @jstoone, да ситуация схожа с одним из наших кейсов
> [EN: @jstoone, yes the situation is similar to one of our cases](https://translate.google.com/?sl=auto&tl=en&text=%D0%B4%D0%B0%20%D1%81%D0%B8%D1%82%D1%83%D0%B0%D1%86%D0%B8%D1%8F%20%D1%81%D1%85%D0%BE%D0%B6%D0%B0%20%D1%81%20%D0%BE%D0%B4%D0%BD%D0%B8%D0%BC%20%D0%B8%D0%B7%20%D0%BD%D0%B0%D1%88%D0%B8%D1%85%20%D0%BA%D0%B5%D0%B9%D1%81%D0%BE%D0%B2&op=translate)

That's great! Did you try deleting the temporary cache directory, as mentioned in my comment?

**Comment by Skreiphoff** [comment]
@jstoone no, we made a decision to stay on version 2.4.3, because an error occurred in another application, we do not process the value in the queue, which, as we assume, is also associated with the slince library

**Comment by jstoone** [comment]
I see. But you don't get any exceptions from the library? If not I might suggest that we close this issue, and update the upgrade guide.
